import "./globals.css";

import type { Metadata } from "next";
// import { Provider } from "react-redux";
import { store } from "./redux/store";

export const metadata: Metadata = {
  title: "trashmails",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mx-10 my-10 bg-gradient-to-tr from-gray-900 via-gray-800 to-gray-400">
        {/* <Provider store={store}> */}
          {children}
        {/* </Provider> */}
      </body>
    </html>
  );
}
